services: # docker compose expects this
    app: #custom key name
#        image: python:latest
        build:
            context:  .

            dockerfile: Dockerfile
        ports:
            -   8000:8000
            -   3000:8000
        command: python -m http.server 8000
