services: # dockers compose expects
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/src:/app
  static_html:
    build:
        context:  ./static_html
        dockerfile: static.Dockerfile
    ports:
            -  8000:8000
            -  3000:8000
    command: python -m http.server 8000
    volumes:
            - ./static_html/src:/app